### ISSUE TITLE
opens, but options don't do anything.

### ISSUE THREAD

**Issue by g7755726** [nico78916/TrollMenuLethalCompany#1]
i open up the menu and when i select a player to try to spawn an enemy or a landmine etc it doesn't do anything.

**Comment by nico78916** [comment]
Were you the host ?
The system will choose the closest vent (when inside) and the closest spawn point (when outside) relative to the player.

**Comment by g7755726** [comment]
Yes i was the host and i even tested it to myself and nothing

**Comment by nico78916** [comment]
Fixed !
